### PR TITLE
offline download

### PR DESCRIPTION
**Pull request by Project516**

### CODE REVIEW

**Comment by dinguschan-owo** [comment]
Before I merge, can you specify what you changed?

**Comment by Project516** [comment]
i added other vercel domains i deployed, and made a offline download with the css and js in it

**Comment by Project516** [comment]
sorry for the bad comments

**Comment by Project516** [comment]
i did not change ur cursing btw

**Comment by dinguschan-owo** [comment]
> i added other vercel domains i deployed, and made a offline download with the css and js in it

what do you mean offline download, like the download button I added? also if I could get your email or phone number it would be easier to contact u on changes

**Comment by Project516** [comment]
do u have discord?

**Comment by dinguschan-owo** [comment]
> do u have discord?

my username is dinguschan_owo

**Comment by Project516** [comment]
also the offline button downloaded the html without the css and js so a make a new file with it in it called yee.html in the d0wnloads folder

**Pull request merged**
