### PR TITLE
yay i fixed it

### PR DESCRIPTION
**Pull request by Project516**

### CODE REVIEW

**Comment by Project516** [comment]
it works!!!

**Review by dinguschan-owo — COMMENTED** [review]
this will not work, because it fetches from the directory "d0wnload" which is not available on the internet. if you hosted that on a file hosting site, the fetched it it would work. think making a new repo, the fetching the raw code. if you fetched from like pastebin it wouldn't work because paste bin doesn't like web scrapers, wheras Github allows scraping on raw files (raw.githubusercontent.com/user/file.type) because many projects fetch other cdns and things

**Comment by Project516** [comment]
i tested it on the vercel.apps just go too yeedee.vercel.app try it for urself

**Comment by Project516** [comment]
@dinguschan-owo

**Comment by dinguschan-owo** [comment]
again, that's because it on ur device

**Comment by Project516** [comment]
did u try it urself?

**Comment by dinguschan-owo** [comment]
ok I stand corrected, it works on every device, but that's because you are fetching from the same repo, from a file IN the repo

**Comment by Project516** [comment]
thats the point

**Comment by dinguschan-owo** [comment]
?? wdym

**Comment by Project516** [comment]
if the domain githubusercontent is blocked the it wont work

**Comment by dinguschan-owo** [comment]
I thought u wanted it to fetch from itself, not from a file in the repo?

**Comment by dinguschan-owo** [comment]
> if the domain githubusercontent is blocked the it wont work

...

**Comment by dinguschan-owo** [comment]
> if the domain githubusercontent is blocked the it wont work

then how does dingusprxy work

**Comment by Project516** [comment]
nah as long as it gets the download then its fine : )

**Comment by dinguschan-owo** [comment]
if u have gogaurdian or securly it blocks ur user id, sending a javascript bot to find and take it back will not be blocked

**Comment by dinguschan-owo** [comment]
as long as u do not visit rawgithubusercontent urself

**Comment by Project516** [comment]
it could be blocked on the network

**Comment by Project516** [comment]
thats what happend for me

**Comment by dinguschan-owo** [comment]
shit really then I have to update dingusproxy send a screenreocrding

**Pull request closed without merging**
